### ISSUE TITLE
Trouble running LiveStats - logger version issue?

### ISSUE THREAD

**Issue by bertinmayer** [Woutrrr/Omnik-Data-Logger#34]
Hi guys,

any idea on how to fix the following error

Bertins-Air-2:first bertinmayer$ python LiveStats.py
2018-08-27 11:32:54,146 DEBUG Importing output plugin ConsoleOutput
2018-08-27 11:32:54,148 INFO connecting to 192.168.178.30 port 80
2018-08-27 11:32:59,249 INFO ID: 
2018-08-27 11:32:59,249 DEBUG Run pluginConsoleOutput
ID: 
Traceback (most recent call last):
  File "LiveStats.py", line 17, in <module>
    omnik_exporter.run()
  File "/Users/bertinmayer/Omnik-Data-Logger/first/OmnikExport.py", line 82, in run
    plugin.process_message(msg)
  File "/Users/bertinmayer/Omnik-Data-Logger/first/outputs/ConsoleOutput.py", line 15, in process_message
    print "E Today: {0:>5}   Total: {1:<5}".format(msg.e_today, msg.e_total)
  File "/Users/bertinmayer/Omnik-Data-Logger/first/InverterMsg.py", line 186, in e_today
    return self.__get_short(69, 100)  # Divide by 100
  File "/Users/bertinmayer/Omnik-Data-Logger/first/InverterMsg.py", line 38, in __get_short
    num = struct.unpack('!H', self.raw_msg[begin:begin + 2])[0]
struct.error: unpack requires a string argument of length 2

**Comment by XtheOne** [comment]
You should not connect to port 80, leave the default.
