### ISSUE TITLE
OmnikExport error

### ISSUE THREAD

**Issue by hlubach** [Woutrrr/Omnik-Data-Logger#43]
Nieuwe provider ,dus nieuwe instelling etc.
Die dus aangepast 
LiveStats geeft de opbrengst weer maar OmnikExport  antwoord met een fout 

LibreELEC:~/omnik # python OmnikExport.py
2020-05-28 10:38:00,574 DEBUG Importing output plugin PVoutputOutput
2020-05-28 10:38:00,722 INFO connecting to 192.168.2.14 port 8899
2020-05-28 10:38:01,433 INFO ID: NLDN2020132S2067
2020-05-28 10:38:01,434 DEBUG Run pluginPVoutputOutput
LibreELEC:~/omnik # python OmnikExport.py
2020-05-28 10:40:21,220 DEBUG Importing output plugin PVoutputOutput
2020-05-28 10:40:21,372 INFO connecting to 192.168.2.14 port 8899
2020-05-28 10:40:22,014 INFO ID: NLDN2020132S2067
2020-05-28 10:40:22,016 DEBUG Run pluginPVoutputOutput
2020-05-28 10:40:22,018 INFO Uploading to PVoutput
Traceback (most recent call last):
  File "OmnikExport.py", line 170, in <module>
    omnik_exporter.run()
  File "OmnikExport.py", line 82, in run
    plugin.process_message(msg)
  File "/storage/omnik/outputs/PVoutputOutput.py", line 49, in process_message
    response = urllib2.urlopen(request_object)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
urllib2.HTTPError: HTTP Error 403: Forbidden

Wat kan er fout zijn

**Comment by steggenhellgood** [comment]
I have setup my Synology NAS to run this as a scheduled job every 5 mins between 6am-9pm and uploads the results to pvoutput. Its very sporadic if it runs successfully or with the http 403 forbidden error and its started for me on May 4th.
