### ISSUE TITLE
ConfigParser

### ISSUE THREAD

**Issue by eterpstra** [Woutrrr/Omnik-Data-Logger#46]
Hoi Wouter,

Ik probeer de omnik uit te lezen. Ik heb de stappen gevolgd.  Echter met python LiveStats.py gaat het al fout:

```
 File "/home/user/Omnik-Data-Logger/OmnikExport.py", line 11, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```

Enig idee wat ik fout doe ? ik heb via pip geprobeerd om ConfigParser  te installeren, maar dit was al geinstalleerd.

**Comment by Maxvani** [comment]
Niet zeker of het nog nodig is, maar ConfigParser is van naam veranderd naar 'configparser' dus als je regel 11 veranderd van `import ConfigParser` naar 'import configparser as ConfigParser' zou het weer moeten werken

**Comment by p4r4ll4x** [comment]
Ik heb hetzelfde probleem.
Na wijzigen van OmnikExport.py krijg ik volgende fout:

```
Traceback (most recent call last):
  File "/home/pi/OmnikDataLogger/Omnik-Data-Logger/LiveStats.py", line 7, in <module>
    import OmnikExport
  File "/home/pi/OmnikDataLogger/Omnik-Data-Logger/OmnikExport.py", line 14, in <module>
    import InverterMsg  # Import the Msg handler
  File "/home/pi/OmnikDataLogger/Omnik-Data-Logger/InverterMsg.py", line 73
    print self.__get_short(59)
          ^
SyntaxError: invalid syntax
```

**Comment by manjh** [comment]
Zelfde probleem hier. Alles werkte al jaren prima, tot ik opmerkte dat na 10 februari geen enkele waarde meer doorkwam. 
Gekeken op de R-Pi: ConfigParser missing. Wijzigen naar configparser hielp niet.  

Heb ook gekeken naar het alternatief, maar ik denk dat mijn inverter te oud is (bijna 10 jaar). Ik kan nergens een lokaal web UI vinden. 

Advies?

**Comment by manjh** [comment]
Is er hoop op een oplossing, of kan ik beter een andere manier zoeken?

**Comment by yohancourbe** [comment]
The code of this repository is very old, it's unmaintained since almost 10 years. ConfigParser is not supported on Python 2 anymore, the code needs to be upgraded to Python 3.

**Comment by sincze** [comment]
This is what I am using: https://github.com/micromys/Omnik/blob/master/inverter_class.php

**Comment by manjh** [comment]
OK, thanks. After a bit of searching I found Inverter-Data-Logger.
Works great.
